---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-bluefin
description: My personal bluefin-dx image

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: gts

modules:
  - type: bling
    install:
      - 1password

  - type: rpm-ostree
    repos:
      - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    keys:
      - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    install:
      - sublime-merge
    optfix:
      - sublime_merge

  - type: fonts
    fonts:
      nerd-fonts:
        - CascadiaCode
        - CascadiaMono

  - type: signing
