---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-bluefin
description: My personal bluefin-dx image

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: gts

modules:
  - type: bling
    install:
      - 1password

  - type: fonts
    fonts:
      nerd-fonts:
        - CaskaydiaCove
        - CaskaydiaMono

  - type: signing
